pipeline {
   agent any
  stages {
    stage('back-end') {
      agent {
        docker {image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'nose:15-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
